import type { Chapter } from "@/lib/types";

// 問題は下記の実在教材の設問・解答をもとに作成（AIによる自由生成は行っていない）。
// - 宮城県教育センター「わくわくワーク」小学4年 算数 単元13「小数のかけ算とわり算」
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/40.els4.kaitou.13.1hop.pdf
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/41.els4.kaitou.13.2stp.pdf
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/42.els4.kaitou.13.3jmp.pdf
export const g4DecimalMultiplicationDivision: Chapter = {
  id: "g4-decimal-multiplication-division",
  grade: "小学4年",
  title: "小数のかけ算とわり算",
  explanation: {
    summary: `小数×整数の計算は、いったん小数点がないものとして整数どうしのかけ算をして、あとから小数点をうつ位置を決めます。例えば1.2×5は、12×5=60を計算してから、1.2の小数点の位置にあわせて6.0（＝6）とします。

小数÷整数の計算は、整数のわり算と同じように筆算し、商の小数点はわられる数の小数点にそろえてうちます。わり切れないときは、0をつけたして「わり切れるまで」計算を続けることもできます。

計算のじゅんじょ（かっこの中→かけ算・わり算→たし算・ひき算）は、小数が混ざった式でも同じように使います。

くらべられる量をもとにする量でわると、「何倍か」を求めることができます（比べる量÷もとにする量＝何倍）。`,
    keyPoints: [
      "小数×整数：整数のかけ算として計算し、あとから小数点の位置を決める",
      "小数÷整数：整数のわり算と同じように筆算し、商の小数点はわられる数の小数点にそろえる",
      "わり切れないときは0をつけたして、わり切れるまで計算できる",
      "計算のじゅんじょ（かっこ→かけ算・わり算→たし算・ひき算）は小数でも同じ",
      "何倍かを求めるときは、比べる量÷もとにする量　で計算する",
    ],
    notebookExample: {
      question: "例：1.2×5を計算する",
      lines: [
        "小数点がないものとして計算する：12×5=60",
        "1.2の小数第一位にあわせて小数点をうつ：6.0",
        "答え：6",
      ],
    },
  },
  practiceProblems: [
    {
      id: "g4-decimalmuldiv-easy-1",
      difficulty: "easy",
      question: "0.2 × 4 = ？",
      answer: "0.8",
      steps: ["2×4=8として計算する", "小数点をうつと0.8"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-easy-2",
      difficulty: "easy",
      question: "1.2 × 5 = ？",
      answer: "6",
      steps: ["12×5=60として計算する", "小数点をうつと6.0＝6"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-1",
      difficulty: "normal",
      question: "2.4 ÷ 2 = ？",
      answer: "1.2",
      steps: ["24÷2=12として計算する", "小数点をうつと1.2"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-2",
      difficulty: "normal",
      question: "0.2L入りのジュースを8個買いました。ジュースは、ぜんぶで何Lありますか。",
      answer: "1.6L",
      steps: ["0.2 × 8 = 1.6", "1.6L"],
      tags: ["小数×整数", "文章題"],
    },
  ],
  assessmentProblems: [
    {
      id: "g4-decimalmuldiv-easy-3",
      difficulty: "easy",
      question: "0.3 × 5 = ？",
      answer: "1.5",
      steps: ["3×5=15として計算する", "小数点をうつと1.5"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-3",
      difficulty: "normal",
      question: "0.4 × 6 = ？",
      answer: "2.4",
      steps: ["4×6=24として計算する", "小数点をうつと2.4"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-4",
      difficulty: "normal",
      question: "2.5 ÷ 5 = ？",
      answer: "0.5",
      steps: ["25÷5=5として計算する", "小数点をうつと0.5"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-5",
      difficulty: "normal",
      question: "3.9 ÷ 3 = ？",
      answer: "1.3",
      steps: ["39÷3=13として計算する", "小数点をうつと1.3"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-6",
      difficulty: "normal",
      question: "2.4 ÷ 3 = ？",
      answer: "0.8",
      steps: ["24÷3=8として計算する", "小数点をうつと0.8"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-7",
      difficulty: "normal",
      question: "6 + 0.5 × 2 = ？",
      answer: "7",
      steps: ["かけ算を先に計算する", "0.5 × 2 = 1", "6 + 1 = 7"],
      tags: ["計算の順序"],
    },
    {
      id: "g4-decimalmuldiv-normal-8",
      difficulty: "normal",
      question: "5.6 × 30 = ？",
      answer: "168",
      steps: ["56×30=1680として計算する", "小数点をうつと168.0＝168"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-9",
      difficulty: "normal",
      question: "0.7 × 87 = ？",
      answer: "60.9",
      steps: ["7×87=609として計算する", "小数点をうつと60.9"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-hard-1",
      difficulty: "hard",
      question: "8.46 × 36 = ？",
      answer: "304.56",
      steps: ["846×36=30456として計算する", "小数点をうつと304.56"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-10",
      difficulty: "normal",
      question: "58.4 ÷ 4 = ？",
      answer: "14.6",
      steps: ["584÷4=146として計算する", "小数点をうつと14.6"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-normal-11",
      difficulty: "normal",
      question: "21.6 ÷ 27 = ？",
      answer: "0.8",
      steps: ["216÷27=8として計算する", "小数点をうつと0.8"],
      tags: ["小数÷整数"],
    },
    {
      id: "g4-decimalmuldiv-hard-2",
      difficulty: "hard",
      question: "56.4 ÷ 24 をわり切れるまで計算しましょう。",
      answer: "2.35",
      steps: ["筆算で0をつけたしながら計算を続ける", "56.4 ÷ 24 = 2.35"],
      tags: ["小数÷整数（わり切れるまで）"],
    },
    {
      id: "g4-decimalmuldiv-hard-3",
      difficulty: "hard",
      question: "44.77 ÷ 55 をわり切れるまで計算しましょう。",
      answer: "0.814",
      steps: ["筆算で0をつけたしながら計算を続ける", "44.77 ÷ 55 = 0.814"],
      tags: ["小数÷整数（わり切れるまで）"],
    },
    {
      id: "g4-decimalmuldiv-hard-4",
      difficulty: "hard",
      question: "2.4kgのさとうを、5つのふくろに等分して入れます。1ふくろのさとうの重さは何kgになりますか。",
      answer: "0.48kg",
      steps: ["2.4 ÷ 5 = 0.48", "0.48kg"],
      tags: ["小数÷整数", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-normal-12",
      difficulty: "normal",
      question: "たて16.2cm、横4cmの長方形の面積は何c㎡ですか。",
      answer: "64.8c㎡",
      steps: ["長方形の面積＝たて×横", "16.2 × 4 = 64.8", "64.8c㎡"],
      tags: ["小数×整数", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-normal-13",
      difficulty: "normal",
      question: "1日で21.5kgの草を食べるヤギがいます。このヤギは1週間では何kgの草を食べますか。",
      answer: "150.5kg",
      steps: ["1週間＝7日間", "21.5 × 7 = 150.5", "150.5kg"],
      tags: ["小数×整数", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-normal-14",
      difficulty: "normal",
      question: "白いテープの長さは2mで、赤いテープの長さは5mです。赤いテープの長さは、白いテープの長さの何倍ですか。",
      answer: "2.5倍",
      steps: ["くらべられる量（赤いテープ）÷もとにする量（白いテープ）", "5 ÷ 2 = 2.5", "2.5倍"],
      tags: ["何倍かを求める計算", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-hard-5",
      difficulty: "hard",
      question: "1さつの重さが186gの算数の教科書があります。この教科書37さつの重さは何kgですか。",
      answer: "6.882kg",
      steps: ["186g = 0.186kg", "0.186 × 37 = 6.882", "6.882kg"],
      tags: ["小数×整数", "単位換算", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-hard-6",
      difficulty: "hard",
      question: "面積が58.23㎡で、たての長さが3mの長方形の花だんがあります。この花だんの横の長さは何mですか。",
      answer: "19.41m",
      steps: ["58.23 ÷ 3 = 19.41", "19.41m"],
      tags: ["小数÷整数", "文章題"],
    },
    {
      id: "g4-decimalmuldiv-hard-7",
      difficulty: "hard",
      question: "4.7 × 6 × 3 = ？",
      answer: "84.6",
      steps: ["前から順に計算する", "4.7 × 6 = 28.2", "28.2 × 3 = 84.6"],
      tags: ["小数×整数"],
    },
    {
      id: "g4-decimalmuldiv-hard-8",
      difficulty: "hard",
      question: "8.7 × 66 = ？",
      answer: "574.2",
      steps: ["87×66=5742として計算する", "小数点をうつと574.2"],
      tags: ["小数×整数"],
    },
  ],
};
