import type { Chapter } from "@/lib/types";

// 問題は下記の実在教材の設問・解答をもとに作成（AIによる自由生成は行っていない）。
// - 宮城県教育センター「わくわくワーク」小学4年 算数 単元2「折れ線グラフと表」
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/04.els4.kaitou.02.1hop.pdf
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/05.els4.kaitou.02.2stp.pdf
//   https://www.edu-c.pref.miyagi.jp/tangen/math/ele4_math/answer/06.els4.kaitou.02.3jmp.pdf
export const g4LineGraphs: Chapter = {
  id: "g4-line-graphs",
  grade: "小学4年",
  title: "折れ線グラフと表",
  explanation: {
    summary: `時間とともに変わっていく量（気温・体温など）を表すには「折れ線グラフ」が向いています。折れ線グラフでは、線のかたむきが急なところほど、変化が大きいことを表します。

一方、人数や台数のように、一つ一つの量をくらべるときは「ぼうグラフ」が向いています。

2つのことがら（例：クロールが泳げるか、平泳ぎが泳げるか）を同時に整理するときは、たてとよこに項目を並べた表（二次元表）を使うと、それぞれの組み合わせの人数が一目で分かります。`,
    keyPoints: [
      "時間とともに変わる量＝折れ線グラフ、一つ一つの量をくらべる＝ぼうグラフ",
      "折れ線グラフの線のかたむきが急なところほど、変化が大きい",
      "2つのことがらを同時に整理するときは、たて・よこに項目を並べた表を使う",
      "表の中の数をすべてたすと、調べた全体の人数になる",
    ],
    diagram: {
      kind: "line-graph",
      unit: "℃",
      maxValue: 30,
      yLabels: [0, 10, 20, 30],
      points: [
        { label: "1月", value: 1.6 },
        { label: "2月", value: 0.8 },
        { label: "3月", value: 4.1 },
        { label: "4月", value: 11.0 },
        { label: "5月", value: 13.4 },
        { label: "6月", value: 19.5 },
      ],
    },
    notebookExample: {
      question: "例：クロールが泳げて、平泳ぎが泳げない人は何人か（表から読み取る）",
      lines: [
        "表の「クロール：泳げる」の行、「平泳ぎ：泳げない」の列を見る",
        "その交わるところの数を読む → 13人",
      ],
    },
  },
  practiceProblems: [
    {
      id: "g4-linegraph-easy-1",
      difficulty: "easy",
      question: "気温や体温のように、時間とともに変わっていく量を表すのに向いているグラフは、折れ線グラフとぼうグラフのどちらですか。",
      answer: "折れ線グラフ",
      steps: ["時間とともに変わっていく量を表すには、折れ線グラフが向いている"],
      tags: ["グラフの種類"],
    },
    {
      id: "g4-linegraph-easy-2",
      difficulty: "easy",
      question: "下の表を見て、クロールが泳げて、平泳ぎが泳げない人は何人ですか。",
      answer: "13人",
      figure: {
        kind: "table",
        columns: ["平泳ぎ：泳げる", "平泳ぎ：泳げない"],
        rows: [
          { label: "クロール：泳げる", cells: [9, 13] },
          { label: "クロール：泳げない", cells: [5, 4] },
        ],
      },
      steps: ["「クロール：泳げる」の行と「平泳ぎ：泳げない」の列が交わるところを読む", "13人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-1",
      difficulty: "normal",
      question: "下の表を見て、クロールも平泳ぎも泳げない人は何人ですか。",
      answer: "4人",
      figure: {
        kind: "table",
        columns: ["平泳ぎ：泳げる", "平泳ぎ：泳げない"],
        rows: [
          { label: "クロール：泳げる", cells: [9, 13] },
          { label: "クロール：泳げない", cells: [5, 4] },
        ],
      },
      steps: ["「クロール：泳げない」の行と「平泳ぎ：泳げない」の列が交わるところを読む", "4人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-2",
      difficulty: "normal",
      question: "下の表を見て、クロールが泳げる人は全体で何人ですか。",
      answer: "22人",
      figure: {
        kind: "table",
        columns: ["平泳ぎ：泳げる", "平泳ぎ：泳げない"],
        rows: [
          { label: "クロール：泳げる", cells: [9, 13] },
          { label: "クロール：泳げない", cells: [5, 4] },
        ],
      },
      steps: ["「クロール：泳げる」の行の数をすべてたす", "9 + 13 = 22人"],
      tags: ["表の読み取り"],
    },
  ],
  assessmentProblems: [
    {
      id: "g4-linegraph-easy-3",
      difficulty: "easy",
      question: "自分の1日の体温の変わり方を表すには、折れ線グラフとぼうグラフのどちらがよいですか。",
      answer: "折れ線グラフ",
      steps: ["時間によって変わっていく量なので、折れ線グラフがよい"],
      tags: ["グラフの種類"],
    },
    {
      id: "g4-linegraph-easy-4",
      difficulty: "easy",
      question: "学級全員分の身長を表すには、折れ線グラフとぼうグラフのどちらがよいですか。",
      answer: "ぼうグラフ",
      steps: ["一人一人の量をくらべるので、ぼうグラフがよい"],
      tags: ["グラフの種類"],
    },
    {
      id: "g4-linegraph-easy-5",
      difficulty: "easy",
      question: "宮城県の市町村の人口を表すには、折れ線グラフとぼうグラフのどちらがよいですか。",
      answer: "ぼうグラフ",
      steps: ["一つ一つの市町村の量をくらべるので、ぼうグラフがよい"],
      tags: ["グラフの種類"],
    },
    {
      id: "g4-linegraph-easy-6",
      difficulty: "easy",
      question: "自動車の生産台数の10年間の変わり方を表すには、折れ線グラフとぼうグラフのどちらがよいですか。",
      answer: "折れ線グラフ",
      steps: ["年ごとに変わっていく量なので、折れ線グラフがよい"],
      tags: ["グラフの種類"],
    },
    {
      id: "g4-linegraph-normal-3",
      difficulty: "normal",
      question: "下の表を見て、校庭で切りきずになった人は何人ですか。",
      answer: "3人",
      figure: {
        kind: "table",
        columns: ["校庭", "体育館", "教室", "ろう下", "合計"],
        rows: [
          { label: "すりきず", cells: [3, 1, 2, 2, 8] },
          { label: "うちみ", cells: [1, 1, 0, 1, 3] },
          { label: "切りきず", cells: [3, 0, 2, 0, 5] },
          { label: "ねんざ", cells: [0, 2, 0, 0, 2] },
          { label: "合計", cells: [7, 4, 4, 3, 18] },
        ],
      },
      steps: ["「切りきず」の行、「校庭」の列を読む", "3人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-4",
      difficulty: "normal",
      question: "下の表を見て、ろう下でいちばん多かったけがの種類は何ですか。",
      answer: "すりきず",
      figure: {
        kind: "table",
        columns: ["校庭", "体育館", "教室", "ろう下", "合計"],
        rows: [
          { label: "すりきず", cells: [3, 1, 2, 2, 8] },
          { label: "うちみ", cells: [1, 1, 0, 1, 3] },
          { label: "切りきず", cells: [3, 0, 2, 0, 5] },
          { label: "ねんざ", cells: [0, 2, 0, 0, 2] },
          { label: "合計", cells: [7, 4, 4, 3, 18] },
        ],
      },
      steps: ["「ろう下」の列をくらべる：すりきず2、うちみ1、切りきず0、ねんざ0", "いちばん多いのはすりきず"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-5",
      difficulty: "normal",
      question: "下の表を見て、いちばんけがの多かった場所はどこですか。",
      answer: "校庭",
      figure: {
        kind: "table",
        columns: ["校庭", "体育館", "教室", "ろう下", "合計"],
        rows: [
          { label: "すりきず", cells: [3, 1, 2, 2, 8] },
          { label: "うちみ", cells: [1, 1, 0, 1, 3] },
          { label: "切りきず", cells: [3, 0, 2, 0, 5] },
          { label: "ねんざ", cells: [0, 2, 0, 0, 2] },
          { label: "合計", cells: [7, 4, 4, 3, 18] },
        ],
      },
      steps: ["合計の行をくらべる：校庭7、体育館4、教室4、ろう下3", "いちばん多いのは校庭"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-6",
      difficulty: "normal",
      question: "下の表を見て、さか上がりができる人は何人ですか。",
      answer: "6人",
      figure: {
        kind: "table",
        columns: ["足かけ上がり：できる", "足かけ上がり：できない"],
        rows: [
          { label: "さか上がり：できる", cells: [3, 3] },
          { label: "さか上がり：できない", cells: [6, 2] },
        ],
      },
      steps: ["「さか上がり：できる」の行をすべてたす", "3 + 3 = 6人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-7",
      difficulty: "normal",
      question: "下の表を見て、足かけ上がりも、さか上がりもできない人は何人ですか。",
      answer: "2人",
      figure: {
        kind: "table",
        columns: ["足かけ上がり：できる", "足かけ上がり：できない"],
        rows: [
          { label: "さか上がり：できる", cells: [3, 3] },
          { label: "さか上がり：できない", cells: [6, 2] },
        ],
      },
      steps: ["「さか上がり：できない」の行と「足かけ上がり：できない」の列が交わるところを読む", "2人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-normal-8",
      difficulty: "normal",
      question: "下の表を見て、先週も今週もかりた人は何人ですか。",
      answer: "10人",
      figure: {
        kind: "table",
        columns: ["先週：かりた", "先週：かりない"],
        rows: [
          { label: "今週：かりた", cells: [10, 7] },
          { label: "今週：かりない", cells: [8, 12] },
        ],
      },
      steps: ["「今週：かりた」の行と「先週：かりた」の列が交わるところを読む", "10人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-hard-1",
      difficulty: "hard",
      question: "下の表を見て、先週かりなかった人は何人ですか。",
      answer: "19人",
      figure: {
        kind: "table",
        columns: ["先週：かりた", "先週：かりない"],
        rows: [
          { label: "今週：かりた", cells: [10, 7] },
          { label: "今週：かりない", cells: [8, 12] },
        ],
      },
      steps: ["「先週：かりない」の列をすべてたす", "7 + 12 = 19人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-hard-2",
      difficulty: "hard",
      question: "下の表を見て、このクラスの人数は何人ですか。",
      answer: "37人",
      figure: {
        kind: "table",
        columns: ["先週：かりた", "先週：かりない"],
        rows: [
          { label: "今週：かりた", cells: [10, 7] },
          { label: "今週：かりない", cells: [8, 12] },
        ],
      },
      steps: ["表の中のすべての人数をたす", "10 + 7 + 8 + 12 = 37人"],
      tags: ["表の読み取り", "文章題"],
    },
    {
      id: "g4-linegraph-hard-3",
      difficulty: "hard",
      question: "下の表を見て、男のきょうだいも女のきょうだいもいない人は何人ですか。",
      answer: "4人",
      figure: {
        kind: "table",
        columns: ["男のきょうだい：いる", "男のきょうだい：いない", "合計"],
        rows: [
          { label: "女のきょうだい：いる", cells: [6, 19, 25] },
          { label: "女のきょうだい：いない", cells: [10, 4, 14] },
          { label: "合計", cells: [16, 23, 39] },
        ],
      },
      steps: ["「女のきょうだい：いない」の行と「男のきょうだい：いない」の列が交わるところを読む", "4人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-hard-4",
      difficulty: "hard",
      question: "下の表を見て、女のきょうだいがいて、男のきょうだいがいない人は何人ですか。",
      answer: "19人",
      figure: {
        kind: "table",
        columns: ["男のきょうだい：いる", "男のきょうだい：いない", "合計"],
        rows: [
          { label: "女のきょうだい：いる", cells: [6, 19, 25] },
          { label: "女のきょうだい：いない", cells: [10, 4, 14] },
          { label: "合計", cells: [16, 23, 39] },
        ],
      },
      steps: ["「女のきょうだい：いる」の行と「男のきょうだい：いない」の列が交わるところを読む", "19人"],
      tags: ["表の読み取り"],
    },
    {
      id: "g4-linegraph-hard-5",
      difficulty: "hard",
      question: "下の折れ線グラフは多賀城市の月別平均気温です。気温がいちばん高い月は何月で、何℃ですか。",
      answer: "8月、25℃",
      figure: {
        kind: "line-graph",
        unit: "℃",
        maxValue: 30,
        yLabels: [0, 10, 20, 30],
        points: [
          { label: "1月", value: 1.6 },
          { label: "2月", value: 0.8 },
          { label: "3月", value: 4.1 },
          { label: "4月", value: 11.0 },
          { label: "5月", value: 13.4 },
          { label: "6月", value: 19.5 },
          { label: "7月", value: 21.4 },
          { label: "8月", value: 25.0 },
          { label: "9月", value: 21.5 },
          { label: "10月", value: 16.3 },
          { label: "11月", value: 9.5 },
          { label: "12月", value: 1.8 },
        ],
      },
      steps: ["グラフの中でいちばん高い点を探す", "8月の25.0℃がいちばん高い"],
      tags: ["折れ線グラフの読み取り"],
    },
    {
      id: "g4-linegraph-hard-6",
      difficulty: "hard",
      question: "上と同じ折れ線グラフを見て、気温がいちばん低い月は何月で、何℃ですか。",
      answer: "2月、0.8℃",
      figure: {
        kind: "line-graph",
        unit: "℃",
        maxValue: 30,
        yLabels: [0, 10, 20, 30],
        points: [
          { label: "1月", value: 1.6 },
          { label: "2月", value: 0.8 },
          { label: "3月", value: 4.1 },
          { label: "4月", value: 11.0 },
          { label: "5月", value: 13.4 },
          { label: "6月", value: 19.5 },
          { label: "7月", value: 21.4 },
          { label: "8月", value: 25.0 },
          { label: "9月", value: 21.5 },
          { label: "10月", value: 16.3 },
          { label: "11月", value: 9.5 },
          { label: "12月", value: 1.8 },
        ],
      },
      steps: ["グラフの中でいちばん低い点を探す", "2月の0.8℃がいちばん低い"],
      tags: ["折れ線グラフの読み取り"],
    },
    {
      id: "g4-linegraph-hard-7",
      difficulty: "hard",
      question: "上と同じ折れ線グラフを見て、いちばん高い月といちばん低い月の気温のちがいは何℃ですか。",
      answer: "24.2℃",
      figure: {
        kind: "line-graph",
        unit: "℃",
        maxValue: 30,
        yLabels: [0, 10, 20, 30],
        points: [
          { label: "1月", value: 1.6 },
          { label: "2月", value: 0.8 },
          { label: "3月", value: 4.1 },
          { label: "4月", value: 11.0 },
          { label: "5月", value: 13.4 },
          { label: "6月", value: 19.5 },
          { label: "7月", value: 21.4 },
          { label: "8月", value: 25.0 },
          { label: "9月", value: 21.5 },
          { label: "10月", value: 16.3 },
          { label: "11月", value: 9.5 },
          { label: "12月", value: 1.8 },
        ],
      },
      steps: ["いちばん高い8月の25.0℃から、いちばん低い2月の0.8℃をひく", "25.0 - 0.8 = 24.2℃"],
      tags: ["折れ線グラフの読み取り"],
    },
    {
      id: "g4-linegraph-hard-8",
      difficulty: "hard",
      question: "上と同じ折れ線グラフを見て、気温がいちばん変化するのは、何月と何月の間ですか（線のかたむきがいちばん急なところ）。",
      answer: "11月と12月の間",
      figure: {
        kind: "line-graph",
        unit: "℃",
        maxValue: 30,
        yLabels: [0, 10, 20, 30],
        points: [
          { label: "1月", value: 1.6 },
          { label: "2月", value: 0.8 },
          { label: "3月", value: 4.1 },
          { label: "4月", value: 11.0 },
          { label: "5月", value: 13.4 },
          { label: "6月", value: 19.5 },
          { label: "7月", value: 21.4 },
          { label: "8月", value: 25.0 },
          { label: "9月", value: 21.5 },
          { label: "10月", value: 16.3 },
          { label: "11月", value: 9.5 },
          { label: "12月", value: 1.8 },
        ],
      },
      steps: ["となりあう月どうしの差がいちばん大きいところを探す", "11月(9.5℃)と12月(1.8℃)の差は7.7℃でいちばん大きい"],
      tags: ["折れ線グラフの読み取り"],
    },
  ],
};
